{% set name = "nrtk" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nrtk-{{ version }}.tar.gz
  sha256: e636c450b535ebb10ce9a8bf9010badd501dca3e8ccb6c291544da03b6768197

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<2.0
    - pillow >=10.3.0
    - pybsm >=0.10.1
    - setuptools >=65.6.1
    - scikit-image >=0.20
    - smqtk-classifier >=0.19.0
    - smqtk-core >=0.19
    - smqtk-detection >=0.19.0
    - smqtk-image-io >=0.17.1
    - tqdm >=4.64
    - typing-extensions >=4.5.0
    - pycocotools >=2.0.6
test:
  imports:
    - nrtk
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: nrtk
  - name: nrtk-graphics
    requirements:
      host:
        - python
      run:
        - python
        - py-opencv >=4.6.0
        - {{ pin_subpackage('nrtk', exact=True) }}
    test:
      imports:
        - nrtk
        - cv2
      commands:
        - pip check
      requires:
        - pip
  - name: nrtk-headless
    requirements:
      host:
        - python
      run:
        - python
        - opencv >=4.6.0
        - {{ pin_subpackage('nrtk', exact=True) }}
    test:
      imports:
        - nrtk
        - cv2
      commands:
        - pip check
      requires:
        - pip
        - libopencv *=headless*  # [not win]

about:
  home: https://pypi.org/project/nrtk/
  summary: |
    The nrtk package is an open source toolkit for evaluating the natural robustness of
    computer vision algorithms to various perturbations, including sensor-specific
    changes to camera focal length, aperture diameter, etc
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alexander-lynch
    - eveenhuis
    - bjrichardwebster
    - Purg
    - barry-ravichandran
