{% set name = "nrtk" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nrtk-{{ version }}.tar.gz
  sha256: 3d764edd9ee7bb368695ec445dd198a0f25dfbe32445f0e9db0adb6322d00bbb

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22,<2.0
    - pillow >=10.3.0
    - scikit-image >=0.20
    - smqtk-classifier >=0.19.0
    - smqtk-core >=0.19
    - smqtk-detection >=0.19.0
    - smqtk-image-io >=0.17.1
    - tqdm >=4.64
    - pycocotools >=2.0.6
test:
  imports:
    - nrtk
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: nrtk
  - name: nrtk-graphics
    requirements:
      host:
        - python
      run:
        - python
        - pybsm-graphics >=0.8.0
        - {{ pin_subpackage('nrtk', exact=True) }}
    test:
      imports:
        - nrtk
      commands:
        - pip check
      requires:
        - pip
  - name: nrtk-headless
    requirements:
      host:
        - python
      run:
        - python
        - pybsm-headless >=0.8.0
        - {{ pin_subpackage('nrtk', exact=True) }}
    test:
      imports:
        - nrtk
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://pypi.org/project/nrtk/
  summary: |
    The nrtk package is an open source toolkit for evaluating the natural robustness of
    computer vision algorithms to various perturbations, including sensor-specific
    changes to camera focal length, aperture diameter, etc
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - alexander-lynch
    - eveenhuis
    - bjrichardwebster
    - Purg
    - barry-ravichandran
